import katana from '../../assets/katana-154939_1280.png';
import buddha from '../../assets/buddha-148533_1280.png';
import book from '../../assets/book-2024278_1280.png';
import board from '../../assets/board-48117_1280.png';
import { Product } from '../../models/Product';

export const products: Product[] = [
  {
    name: 'Statuette',
    price: 150.0,
    imgPath: `${buddha}`,
    category: 'Statuette',
    universe: 'Japon1',
    product_creation_date: 1694295379,
  },
  {
    name: 'Katana',
    price: 1500.0,
    imgPath: `${katana}`,
    category: 'Arme',
    universe: 'Japon2',
    product_creation_date: 1694868179,
  },
  {
    name: 'Omanga Tome 01',
    price: 60.0,
    imgPath: `${book}`,
    category: 'Livre',
    universe: 'Japon3',
    product_creation_date: 1694695379,
  },
  {
    name: 'Carte Omanga',
    price: 80.0,
    imgPath: `${board}`,
    category: 'Carte',
    universe: 'Japon4',
    product_creation_date: 1694795379,
  },
  {
    name: 'Statuette',
    price: 800.0,
    imgPath: `${buddha}`,
    category: 'Statuette',
    universe: 'Japon1',
    product_creation_date: 1694595379,
  },
  {
    name: 'Katana',
    price: 600.0,
    imgPath: `${katana}`,
    category: 'Arme',
    universe: 'Japon2',
    product_creation_date: 1694595379,
  },
  {
    name: 'Omanga Tome 01',
    price: 500.0,
    imgPath: `${book}`,
    category: 'Livre',
    universe: 'Japon3',
    product_creation_date: 1694495379,
  },
  {
    name: 'Carte Omanga',
    price: 1000.0,
    imgPath: `${board}`,
    category: 'Carte',
    universe: 'Japon4',
    product_creation_date: 1694395379,
  },
  {
    name: 'Statuette',
    price: 500.0,
    imgPath: `${buddha}`,
    category: 'Statuette',
    universe: 'Japon1',
    product_creation_date: 1694395379,
  },
  {
    name: 'Katana',
    price: 220.0,
    imgPath: `${katana}`,
    category: 'Arme',
    universe: 'Japon2',
    product_creation_date: 1694195379,
  },
  {
    name: 'Omanga Tome 01',
    price: 15.0,
    imgPath: `${book}`,
    category: 'Livre',
    universe: 'Japon3',
    product_creation_date: 1694295379,
  },
  {
    name: 'Carte Omanga',
    price: 11.0,
    imgPath: `${board}`,
    category: 'Carte',
    universe: 'Japon4',
    product_creation_date: 1694295379,
  },
  {
    name: 'Statuette',
    price: 120.0,
    imgPath: `${buddha}`,
    category: 'Statuette',
    universe: 'Japon1',
    product_creation_date: 1694295379,
  },
  {
    name: 'Katana',
    price: 300.0,
    imgPath: `${katana}`,
    category: 'Arme',
    universe: 'Japon2',
    product_creation_date: 1694295379,
  },
  {
    name: 'Omanga Tome 01',
    price: 10.0,
    imgPath: `${book}`,
    category: 'Livre',
    universe: 'Japon3',
    product_creation_date: 1694295379,
  },
  {
    name: 'Carte Omanga',
    price: 15.0,
    imgPath: `${board}`,
    category: 'Carte',
    universe: 'Japon4',
    product_creation_date: 1694295379,
  },
];
